version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo NO_ARTIFACTS = $NO_ARTIFACTS
      - if [ 1 -eq 1 ]; then echo "Version is same, failing the build process"; export NO_ARTIFACTS=true; fi
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p GATEWAY/bin GATEWAY/lib GATEWAY/conf
      - touch GATEWAY/bin/startup.sh GATEWAY/conf/application.properties
      - cp target/messageUtil-1.0.jar GATEWAY/lib
      - pwd
      - echo "java $Java_details ../lib/messageUtil-1.0.jar">> GATEWAY/bin/startup.sh
artifacts:
  files:
    - 'GATEWAY/**/*'
    - 'appspec.yml'
    - 'start.sh'
    - 'stop.sh'
